ApiCentroMedicoClient/Controllers/CentroMedicoClientController.cs
using ApiCentroMedicoClient.Filters;
using ApiCentroMedicoClient.Models;
using ApiCentroMedicoClient.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ApiCentroMedicoClient.Controllers
{
    public class CentroMedicoClientController : Controller
    {
        private ServiceApiCentroMedicoClient service;
        public CentroMedicoClientController(ServiceApiCentroMedicoClient service)
        {
            this.service = service;
        }

        //Controller , nos muestra una pagina segun el rol.
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorPrincipal()
        {
            int id = int.Parse(this.HttpContext.User.FindFirst("ID").Value);
            Usuario user = await this.service.FindUsuarioAsync(id);
            ViewData["NOMBREUSUARIO"] = user.Nombre;
            //ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            return View();
        }
        [AuthorizeUsers(Policy = "SOLORECEPCIONISTA")]
        public async Task<IActionResult> RecepcionistaPrincipal()
        {
            int id = int.Parse(this.HttpContext.User.FindFirst("ID").Value);
            Usuario user = await this.service.FindUsuarioAsync(id);
            ViewData["NOMBREUSUARIO"] = user.Nombre;
            //ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            return View();
        }
        [AuthorizeUsers(Policy = "SOLOMEDICO")]
        public async Task<IActionResult> MedicoPrincipal()
        {
            int id = int.Parse(this.HttpContext.User.FindFirst("ID").Value);
            Usuario user = await this.service.FindUsuarioAsync(id);
            ViewData["NOMBREUSUARIO"] = user.Nombre;
            //ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            return View();
        }
        [AuthorizeUsers(Policy = "SOLOPACIENTE")]
        public async Task<IActionResult> PacientePrincipal()
        {
            int id = int.Parse(this.HttpContext.User.FindFirst("ID").Value);
            Usuario user = await this.service.FindUsuarioAsync(id);
            ViewData["NOMBREUSUARIO"] = user.Nombre;
            //ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            return View();
        }



        // ============ Controller Administrador ============ //

        //Controller donde recogemos la informacion del administrador y guardamos la nueva. 
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorPerfil()
        {
            int id = int.Parse(this.HttpContext.User.FindFirst("ID").Value);
            Usuario user = await this.service.FindUsuarioAsync(id);
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> AdministradorPerfil(Usuario user)
        {
            await this.service.PutUsuarioAsync(user.Id,user.Nombre,user.Apellido,user.Correo,user.Contra,user.Id_EstadoUsuario,user.Id_TipoUsuario);
            return RedirectToAction("AdministradorPrincipal");
        }

        //Controller donde manejamos los usuarios de la BBDD.
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorListaUsuarios()
        {
            ViewData["TIPOUSUARIO"] = await this.service.GetTipoUsuario();
            ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            List<Usuario> usuarios = await this.service.GetUsuariosAsync();
            return View(usuarios);
        }
        [HttpPost]
        public async Task<IActionResult> AdministradorListaUsuarios(int tipoUsuario)
        {
            ViewData["TIPOUSUARIO"] = await this.service.GetTipoUsuario();
            ViewData["IDUSUARIO"] = HttpContext.User.FindFirst(z => z.Type == "ID").Value;
            List<Usuario> usuarios = await this.service.GetUsuariosTipoAsync(tipoUsuario);
            return View(usuarios);
        }

        //Controller donde recogemos 2 parametros, el idusuario y el idtipo.
        //Segun el tipo le redirecciona a otro controller. Esto es necesario porque a la hora de llamar al controller, desde la vista ,
        //no podemos indicarle a cada uno el controller que debe de usar asi que le enviamos uno (este) que redirige automaticamente.

        //Informacion(Details)
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public IActionResult AdministradorInformacion(int idusuario, int idtipo)
        {
            TempData["IDUSUARIOINFO"] = idusuario;
            if (idtipo == 1 || idtipo == 2)
            {
                return RedirectToAction("AdministradorInfoUsuario");
            }
            else if (idtipo == 3)
            {
                return RedirectToAction("AdministradorInfoMedico");
            }
            else
            {
                return RedirectToAction("AdministradorInfoPaciente");
            }
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorInfoUsuario()
        {
            int idusuario = (int)TempData["IDUSUARIOINFO"];
            UsuarioDetallado usuario = await this.service.GetUsuarioDetallado(idusuario);
            return View(usuario);
            
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorInfoMedico()
        {
            int idmedico = (int)TempData["IDUSUARIOINFO"];
            MedicoDetallado medico = await this.service.GetMedicoDetallado(idmedico);
            return View(medico);
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorInfoPaciente()
        {
            int idpaciente = (int)TempData["IDUSUARIOINFO"];
            PacienteDetallado paciente = await this.service.GetPacienteDetallado(idpaciente);
            return View(paciente);
        }

        //Actualizar(Update)
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public IActionResult AdministradorActualizar(int idusuario, int idtipo)
        {
            TempData["IDUSUARIOACTUALIZAR"] = idusuario;
            if (idtipo == 1 || idtipo == 2)
            {
                return RedirectToAction("AdministradorActualizarUsuario");
            }
            else if (idtipo == 3)
            {
                return RedirectToAction("AdministradorActualizarMedico");
            }
            else
            {
                return RedirectToAction("AdministradorActualizarPaciente");
            }
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorActualizarUsuario()
        {
            int idusuario = (int)TempData["IDUSUARIOACTUALIZAR"];
            ViewData["ESTADOS"] = await this.service.GetEstadosAsync();
            Usuario usuario = await this.service.FindUsuarioAsync(idusuario);
            return View(usuario);
        }
        [HttpPost]
        public async Task<IActionResult> AdministradorActualizarUsuario(Usuario user)
        {
            await this.service.PutUsuarioAsync(user.Id, user.Nombre, user.Apellido, user.Correo, user.Contra, user.Id_EstadoUsuario, user.Id_TipoUsuario);
            return RedirectToAction("AdministradorListaUsuarios"); //La vista no redirige al usar el seet alert
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorActualizarMedico()
        {
            int idmedico = (int)TempData["IDUSUARIOACTUALIZAR"];
            ViewData["ESTADOS"] = await this.service.GetEstadosAsync();
            ViewData["ESPECIALIDADES"] = await this.service.GetEspecialidadesAsync();
            Medico medico = await this.service.FindMedicoAsync(idmedico);
            return View(medico);
        }
        [HttpPost]
        public async Task<IActionResult> AdministradorActualizarMedico(Medico medico)
        {
            await this.service.UpdateMedicoAsync(medico.Id,medico.Nombre,medico.Apellido,medico.Correo,medico.Contra,medico.EstadoUsuario,medico.TipoUsuario,medico.Especialidad);
            return RedirectToAction("AdministradorListaUsuarios"); //La vista no redirige al usar el seet alert
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorActualizarPaciente()
        {
            int idpaciente = (int)TempData["IDUSUARIOACTUALIZAR"];
            ViewData["ESTADOS"] = await this.service.GetEstadosAsync();
            Paciente paciente = await this.service.FindPacienteAsync(idpaciente);
            return View(paciente);
        }
        [HttpPost]
        public async Task<IActionResult> AdministradorActualizarPaciente(Paciente pac)
        {
            await this.service.UpdatePacienteAsync(pac.Id,pac.Nombre,pac.Apellido,pac.Correo,pac.Contra,pac.Telefono,pac.Direccion,pac.Edad,pac.Genero,pac.EstadoUsuario,pac.TipoUsuario);
            return RedirectToAction("AdministradorListaUsuarios"); //La vista no redirige al usar el seet alert
        }

        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorEliminarUsuario(int idusuario, int idtipo)
        {
            await this.service.DeleteUsuarioAsync(idusuario,idtipo);
            return RedirectToAction("AdministradorListaUsuarios");
        }

        //Controller que permite crear recepcionista/administrador y medicos.
        [AuthorizeUsers(Policy = "SOLOADMINISTRADOR")]
        public async Task<IActionResult> AdministradorCreateMedico()
        {
            ViewData["ESPECIALIDADES"] = await this.service.GetEspecialidadesAsync();
            return View();
        }

        [HttpPost]

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorFindPacienteCita.cshtml
@model ApiCentroMedicoClient.Models.PacienteDetallado

@{
    ViewData["Title"] = "AdministradorInfoPaciente";
}

<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Informacion Paciente</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorFindCita" asp-route-idcita="@ViewData["CITASELECCIONADA"]"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
</div>
<br />
<hr />
<br />
<div class="card mb-9" style="max-width: 940px;margin:auto">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/iconousuario.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">ID : @Model.Id</li>
                    <li class="list-group-item">Apellido : @Model.Apellido</li>
                    <li class="list-group-item">Correo : @Model.Correo</li>
                    <li class="list-group-item">Contraseña : @Model.Contra</li>
                    <li class="list-group-item">Telefono : @Model.Telefono</li>
                    <li class="list-group-item">Direccion : @Model.Direccion</li>
                    <li class="list-group-item">Edad : @Model.Edad</li>
                    <li class="list-group-item">Genero : @Model.Genero</li>
                    <li class="list-group-item">Estado : @Model.Estado</li>
                    <li class="list-group-item">Tipo : @Model.Tipo</li>
                </ul>
            </div>
        </div>
    </div>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorGetListaCitas.cshtml
@model IEnumerable<ApiCentroMedicoClient.Models.CitaDetallado>

@{
    ViewData["Title"] = "GetListaCitas";
}

<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Lista Citas</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorPrincipal"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
    <br />
    <hr />
    <br />
    <div>
        <h2>Filtros</h2>
        <form method="post">
            <label>Selecciona Fecha Desde</label>
            <input type="date" name="fecha" class="form-control"/>
            <label>Selecciona Fecha Hasta</label>
            <input type="date" name="fechahasta" class="form-control"/>
            <br />
            <button class="btn btn-outline-success">
                Buscar
            </button>
        </form>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fecha)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hora)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SeguimientoCita)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Medico)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Comentario)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hora)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SeguimientoCita)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Medico)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Comentario)
                    </td>
                    <td>
                        <a asp-controller="CentroMedicoClient" asp-action="AdministradorFindCita" asp-route-idcita="@item.Id" class="btn btn-outline-info">Informacion</a>
                        <a asp-controller="CentroMedicoClient" asp-action="AdministradorDeleteCita" asp-route-idcita="@item.Id" class="btn btn-outline-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorInfoMedico.cshtml
@model ApiCentroMedicoClient.Models.MedicoDetallado

@{
    ViewData["Title"] = "AdministradorInfoMedico";
}

<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Informacion Medico</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorListaUsuarios"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
</div>
<br />
<hr />
<br />
<div class="card mb-9" style="max-width: 940px;margin:auto">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/iconousuario.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">ID : @Model.Id</li>
                    <li class="list-group-item">Nombre : @Model.Nombre</li>
                    <li class="list-group-item">Apellido : @Model.Apellido</li>
                    <li class="list-group-item">Correo : @Model.Correo</li>
                    <li class="list-group-item">Contraseña : @Model.Contra</li>
                    <li class="list-group-item">Especialidad : @Model.Especialidad</li>
                    <li class="list-group-item">Estado : @Model.Estado</li>
                    <li class="list-group-item">Tipo : @Model.Tipo</li>
                </ul>
            </div>
        </div>
    </div>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorInfoUsuario.cshtml
@model ApiCentroMedicoClient.Models.UsuarioDetallado

@{
    ViewData["Title"] = "AdministradorInfoUsuario";
}


<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Informacion Usuario</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorListaUsuarios"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
</div>
<br />
<hr />
<br />
<div class="card mb-9" style="max-width: 940px;margin:auto">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/iconousuario.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">ID : @Model.Id</li>
                    <li class="list-group-item">Nombre : @Model.Nombre</li>
                    <li class="list-group-item">Apellido : @Model.Apellido</li>
                    <li class="list-group-item">Correo : @Model.Correo</li>
                    <li class="list-group-item">Contraseña : @Model.Contra</li>
                    <li class="list-group-item">Estado : @Model.Estado</li>
                    <li class="list-group-item">Tipo : @Model.Tipo</li>
                </ul>
            </div>
        </div>
    </div>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorListaPeticionesMedicamentos.cshtml
@model IEnumerable<ApiCentroMedicoClient.Models.PeticionesMedicamentoDetallado>

@{
    ViewData["Title"] = "AdministradorListaPeticionesMedicamentos";
}

<div>
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Lista Peticicones Medicamentos</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorPrincipal"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
    <br />
    <hr />
    <br />
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (PeticionesMedicamentoDetallado petis in Model)
        {
            <div class="col">
                <div class="card h-100">
                    <img src="~/images/iconomedis.png" style="width:80px;height80px;margin:auto" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@petis.NombreMedicamento</h5>
                        <p class="card-text">
                            Medico <b>@petis.NombreMedico @petis.ApellidoMedico</b> con ID: <b>@petis.IdMedico_Solicitante</b> quiere dar de <b>@petis.Estado</b> el medicamento <b>@petis.NombreMedicamento @petis.PetisMedicamentoNombre</b> 
                        </p>
                    </div>
                    <div class="card-footer" style="margin:auto">
                        <a asp-controller="CentroMedicoClient" asp-action="AdministradorAceptarMedicamento"
                           asp-route-idpeticion="@petis.IdPeticion"
                           asp-route-idmedicamento="@petis.IdMedicamento" 
                           asp-route-nombre="@petis.NombreMedicamento@petis.PetisMedicamentoNombre"
                           asp-route-descripcion="@petis.PetisMedicamentoDesc" 
                           asp-route-estado="@petis.PetisMedicamentoEstado"
                           class="btn btn-success">Aceptar
                       </a>
                        <a asp-controller="CentroMedicoClient" asp-action="AdministradorEliminarPeticionMedicamento"
                           asp-route-idpeticion="@petis.IdPeticion"
                           class="btn btn-warning">Denegar
                       </a>
                    </div>

                </div>
            </div>
        }
    </div>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorListaUsuarios.cshtml
@model IEnumerable<ApiCentroMedicoClient.Models.Usuario>

@{
    List<UsuariosTipo> tipos = ViewData["TIPOUSUARIO"] as List<UsuariosTipo>;
    int idusuario = int.Parse(ViewData["IDUSUARIO"].ToString());
}

<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Lista Usuarios</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorPrincipal"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
    <br />
    <hr />
    <br />
    <div>
        <h2>¿ Nuev@s Empleados ?</h2>
        <p class="p-2">
            <b>Si necesitas un médico</b> <a asp-controller="CentroMedicoClient" asp-action="AdministradorCreateMedico" class="text-info">Crear Médico</a>
        </p>
        <p class="p-2">
            <b>Si necesitas un recepcionista o un administrador</b> <a asp-controller="CentroMedicoClient" asp-action="AdministradorCreateUsuario" class="text-info"> Crear Recepcionista/Administrador</a>
        </p>
    </div>
    <br />
    <hr />
    <br />
    <div>
        <h2>Filtros</h2>
        <form method="post">
            <label>Selecciona un ROL</label>
            <select name="tipoUsuario" class="form-select">
                @foreach (UsuariosTipo tipo in tipos)
                {
                    <option value="@tipo.Id">@tipo.Tipo</option>
                }
            </select>
            <br />
            <button class="btn btn-outline-success">
                Buscar
            </button>
        </form>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Correo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.Id != idusuario)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Correo)
                        </td>
                        <td>
                            <a asp-controller="CentroMedicoClient" asp-action="AdministradorInformacion" asp-route-idusuario="@item.Id" asp-route-idtipo="@item.Id_TipoUsuario" class="btn btn-outline-info">Informacion</a>
                            <a asp-controller="CentroMedicoClient" asp-action="AdministradorActualizar" asp-route-idusuario="@item.Id" asp-route-idtipo="@item.Id_TipoUsuario" class="btn btn-outline-warning">Editar</a>
                            <a asp-controller="CentroMedicoClient" asp-action="AdministradorEliminarUsuario" asp-route-idusuario="@item.Id" asp-route-idtipo="@item.Id_TipoUsuario" class="btn btn-outline-danger">Eliminar</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/AdministradorPerfil.cshtml
@model ApiCentroMedicoClient.Models.Usuario

@{
    ViewData["Title"] = "AdministradorPerfil";
}

<div class="container text-center"> @* Usar este class *@
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Perfil</h1>
        <a asp-controller="CentroMedicoClient" asp-action="AdministradorPrincipal"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
    <hr />
    <div>
        <div style="width:60%;margin:auto"> @* Usar este Style *@
            <form asp-action="AdministradorPerfil">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input asp-for="Id" class="form-control" hidden />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Apellido" class="control-label"></label>
                    <input asp-for="Apellido" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Correo" class="control-label"></label>
                    <input asp-for="Correo" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Contra" class="control-label"></label>
                    <input asp-for="Contra" class="form-control" />
                    <span asp-validation-for="Contra" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Id_EstadoUsuario" class="form-control" hidden />
                    <span asp-validation-for="Id_EstadoUsuario" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Id_TipoUsuario" class="form-control" hidden />
                    <span asp-validation-for="Id_TipoUsuario" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</div>

ApiCentroMedicoClient/Views/CentroMedicoClient/MedicoInfoPaciente.cshtml
@model ApiCentroMedicoClient.Models.PacienteDetallado

@{
    ViewData["Title"] = "AdministradorInfoPaciente";
}

<div class="container text-center">
    <div style="display: flex; align-items: center; justify-content: center;">
        <h1 style="margin-right: 10px;">Informacion Paciente</h1>
        <a asp-controller="CentroMedicoClient" asp-action="MedicoMisPacientes"><img src="~/images/iconoflecha.png" style="width:40px;height:40px;"></a>
    </div>
</div>
<br />
<hr />
<br />
<div class="card mb-9" style="max-width: 940px;margin:auto">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/iconousuario.png" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">ID : @Model.Id</li>
                    <li class="list-group-item">Apellido : @Model.Apellido</li>
                    <li class="list-group-item">Correo : @Model.Correo</li>
                    <li class="list-group-item">Contraseña : @Model.Contra</li>
                    <li class="list-group-item">Telefono : @Model.Telefono</li>
                    <li class="list-group-item">Direccion : @Model.Direccion</li>
                    <li class="list-group-item">Edad : @Model.Edad</li>
                    <li class="list-group-item">Genero : @Model.Genero</li>
                    <li class="list-group-item">Estado : @Model.Estado</li>
                    <li class="list-group-item">Tipo : @Model.Tipo</li>
                </ul>
            </div>
        </div>
    </div>
</div>